version: '2'

services:
  squid:
    build:
      context: ../..
      dockerfile: docker/release/Dockerfile
      args:
        app_name: ${PROJECT_NAME}
    ports:
      - "3128"
    environment:
      NO_WHITELIST: ${NO_WHITELIST}
      SQUID_WHITELIST: ${SQUID_WHITELIST}
      AWS_REGIONS: ${AWS_REGIONS}
      SHUTDOWN_LIFETIME: "0"
    container_name: ${ORG_NAME}-${PROJECT_NAME}
    image: ${ORG_NAME}/${PROJECT_NAME}
